server:
  port: 8080
  shutdown: graceful
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true          # 웹 콘솔 활성화
  jpa:
    hibernate:
      ddl-auto: create       # 테이블 자동 생성
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

# Prometheus 설정
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus  # 외부에 노출할 actuator endpoint 설정 (Prometheus 포함)
  endpoint:
    prometheus:
      enabled: true  # /actuator/prometheus 엔드포인트 활성화
  prometheus:
    metrics:
      export:
        enabled: true  # Micrometer가 Prometheus 형식으로 메트릭 내보내도록 설정