spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/temp?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: root
    password: root
  devtools:
    livereload:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update